name: .NET (Dev build)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -r ${{ matrix.target }} --self-contained -f net10.0
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        directory: ${{ github.workspace }}/bin/Release/net10.0/${{ matrix.target }}/publish
        type: 'zip'
        filename: ${{ github.workspace }}/Release-${{ matrix.target }}.zip
    - uses: actions/upload-artifact@v7
      with:
        name: Release-${{ matrix.target }}
        path: ${{ github.workspace }}/Release-${{ matrix.target }}.zip
